# Site settings
title: StartDevelUp
email: hello@startdevelup.com
description: >
  Developing value and creating the future, together with entrepreneurs, accelerators, and incubators - that’s how I spend most of my time. It’s an awesome job.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://startdevelup.com" # the base hostname & protocol for your site
linkedin_username: kristofferolsson
# Build settings
markdown: kramdown
