# Site settings
title: StartDevelUp
email: hello@startdevelup.com

description: > # this means to ignore newlines until "baseurl:"
  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum id quas inventore ducimus doloremque, natus sequi necessitatibus nulla in. Fugiat nihil est ipsam! Eum, ipsum, nihil. Veritatis, labore, repellendus.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://startdevelup.com" # the base hostname & protocol for your site
linkedin_username: kristofferolsson
# Build settings
markdown: kramdown
