# Site settings
title: Krolup!
email: hej@krol.com
description: > # this means to ignore newlines until "baseurl:"
  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum id quas inventore ducimus doloremque, natus sequi necessitatibus nulla in. Fugiat nihil est ipsam! Eum, ipsum, nihil. Veritatis, labore, repellendus.
baseurl: "/krol/" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: kr_ol

# Build settings
markdown: kramdown
